# Generated by Django 4.1.5 on 2025-10-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
